services:
  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    container_name: tildex-backend
  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    container_name: tildex-frontend

